/**
 * This file was generated by kysely-codegen.
 * Please do not edit it manually.
 */

import type { ColumnType } from "kysely";

export type Generated<T> = T extends ColumnType<infer S, infer I, infer U>
  ? ColumnType<S, I | undefined, U>
  : ColumnType<T, T | undefined, T>;

export type Int8 = ColumnType<string, bigint | number | string, bigint | number | string>;

export type Json = JsonValue;

export type JsonArray = JsonValue[];

export type JsonObject = {
  [x: string]: JsonValue | undefined;
};

export type JsonPrimitive = boolean | number | string | null;

export type JsonValue = JsonArray | JsonObject | JsonPrimitive;

export type Timestamp = ColumnType<Date, Date | string, Date | string>;

export interface GhgEvidence {
  created_at: Generated<Timestamp | null>;
  created_by_user_id: string | null;
  file_size: Int8;
  file_url: string;
  id: Generated<string>;
  inventory_id: string | null;
  mime_type: string;
  organization_id: string | null;
  original_name: string;
  scopecategory_id: string | null;
  unit_id: string | null;
  updated_at: Timestamp | null;
}

export interface GhgInventories {
  archived: Generated<boolean>;
  created_at: Generated<Timestamp | null>;
  created_by_user_id: string;
  fiscal_year: number;
  id: Generated<string>;
  organization_id: string;
  updated_at: Timestamp | null;
}

export interface GhgInventoryUnitConfigs {
  controller_unit_id: string | null;
  created_at: Generated<Timestamp | null>;
  hierarchy: number;
  id: Generated<string>;
  inventory_unit_id: string;
  operational_control: boolean;
  percentage_share: number;
  unit_config_id: string | null;
  updated_at: Timestamp | null;
}

export interface GhgInventoryUnits {
  city: string | null;
  cnpj: string | null;
  country: string;
  created_at: Generated<Timestamp | null>;
  id: Generated<string>;
  inventory_id: string;
  name: string;
  sector: string | null;
  state: string | null;
  unit_id: string;
  updated_at: Timestamp | null;
}

export interface GhgScope1category1responses {
  biogenicco2emission: Generated<number>;
  ch4emission: Generated<number>;
  co2emission: Generated<number>;
  created_at: Generated<Timestamp | null>;
  created_by_user_id: string;
  fuel: string;
  id: Generated<string>;
  inventory_id: string;
  n2oemission: Generated<number>;
  name: string;
  period: Generated<string>;
  quantity: number;
  quantity_unit: string | null;
  scopecategory_id: string;
  totalco2emission: Generated<number>;
  unit_id: string;
  updated_at: Timestamp | null;
}

export interface GhgScope1category2responses {
  biogenicco2emission: Generated<number>;
  calcule_approach: Generated<string>;
  ch4emission: Generated<number>;
  co2emission: Generated<number>;
  created_at: Generated<Timestamp | null>;
  created_by_user_id: string;
  distance: number | null;
  fuel: string | null;
  id: Generated<string>;
  inventory_id: string;
  n2oemission: Generated<number>;
  name: string;
  period: Generated<string>;
  quantity: number;
  quantity_unit: string | null;
  scopecategory_id: string;
  totalco2emission: Generated<number>;
  unit_id: string;
  updated_at: Timestamp | null;
  vehicle: string | null;
  year: string | null;
}

export interface GhgScope1category3responses {
  calcule_approach: string | null;
  created_at: Generated<Timestamp | null>;
  created_by_user_id: string;
  device_quantity: number | null;
  device_size: string | null;
  gas_type: string | null;
  id: Generated<string>;
  inventory_id: string;
  modal_type: Generated<string>;
  name: string;
  period: Generated<string>;
  quantity: number;
  quantity_unit: string | null;
  scopecategory_id: string;
  size: string | null;
  totalco2emission: Generated<number>;
  unit_id: string;
  updated_at: Timestamp | null;
}

export interface GhgScope1category4responses {
  calculation_memory: string | null;
  created_at: Generated<Timestamp | null>;
  created_by_user_id: string;
  fuel: string;
  id: Generated<string>;
  inventory_id: string;
  name: string;
  period: Generated<string>;
  quantity: number;
  quantity_unit: string | null;
  scopecategory_id: string;
  totalco2emission: Generated<number>;
  unit_id: string;
  updated_at: Timestamp | null;
}

export interface GhgScope1category5responses {
  created_at: Generated<Timestamp | null>;
  created_by_user_id: string;
  fertilizer: string | null;
  id: Generated<string>;
  inventory_id: string;
  modal_type: string | null;
  n2oemission: Generated<number>;
  name: string | null;
  percentual_nitrogen: number | null;
  period: Generated<string>;
  quantity: number;
  quantity_unit: string | null;
  scopecategory_id: string;
  totalco2emission: Generated<number>;
  unit_id: string;
  updated_at: Timestamp | null;
}

export interface GhgScope1category6responses {
  created_at: Generated<Timestamp | null>;
  created_by_user_id: string;
  fuel: string | null;
  id: Generated<string>;
  inventory_id: string;
  name: string | null;
  period: Generated<string>;
  quantity: number;
  quantity_unit: string | null;
  scopecategory_id: string;
  totalco2emission: Generated<number>;
  unit_id: string;
  updated_at: Timestamp | null;
}

export interface GhgScope1category7responses {
  ch4emission: Generated<number>;
  co2emission: Generated<number>;
  composting: number | null;
  composting_unit: string | null;
  created_at: Generated<Timestamp | null>;
  created_by_user_id: string;
  id: Generated<string>;
  incineration: number | null;
  incineration_unit: string | null;
  inventory_id: string;
  landfill: number | null;
  landfill_unit: string | null;
  n2oemission: Generated<number>;
  name: string | null;
  period: Generated<string>;
  recycling: number | null;
  recycling_unit: string | null;
  residue: string | null;
  scopecategory_id: string;
  totalco2emission: Generated<number>;
  unit_id: string;
  updated_at: Timestamp | null;
}

export interface GhgScope1category8responses {
  biogenicco2emission: Generated<number>;
  ch4emission: Generated<number>;
  co2emission: Generated<number>;
  created_at: Generated<Timestamp | null>;
  created_by_user_id: string;
  effluent_type: string | null;
  final_disposition: string | null;
  flue_gas_released_quantity: number | null;
  has_metane_removed: string | null;
  id: Generated<string>;
  inventory_id: string;
  is_flue_gas_released: string | null;
  metane_destination: string | null;
  n2oemission: Generated<number>;
  name: string | null;
  nitrogen: string | null;
  nitrogen_output: string | null;
  nitrogen_output_quantity: number | null;
  nitrogen_quantity: number | null;
  organic_load: string | null;
  organic_load_output: string | null;
  organic_load_output_quantity: number | null;
  organic_load_quantity: number | null;
  organic_load_removed: number | null;
  period: Generated<string>;
  quantity: number;
  quantity_metane_removed: number | null;
  quantity_unit: string | null;
  scopecategory_id: string;
  totalco2emission: Generated<number>;
  treatment_type: string | null;
  unit_id: string;
  updated_at: Timestamp | null;
}

export interface GhgScope2category1responses {
  co2emission: Generated<number>;
  created_at: Generated<Timestamp | null>;
  created_by_user_id: string;
  id: Generated<string>;
  inventory_id: string;
  period: Generated<string>;
  quantity: number;
  quantity_unit: string | null;
  scopecategory_id: string;
  totalco2emission: Generated<number>;
  unit_id: string;
  updated_at: Timestamp | null;
}

export interface GhgScope2category2responses {
  biogenicco2emission: Generated<number>;
  co2emission: Generated<number>;
  created_at: Generated<Timestamp | null>;
  created_by_user_id: string;
  energy_type: string | null;
  id: Generated<string>;
  inventory_id: string;
  name: string | null;
  period: Generated<string>;
  quantity: number;
  quantity_unit: string | null;
  scopecategory_id: string;
  totalco2emission: Generated<number>;
  unit_id: string;
  updated_at: Timestamp | null;
}

export interface GhgScope2category3responses {
  biogenicco2emission: Generated<number>;
  ch4emission: Generated<number>;
  co2emission: Generated<number>;
  created_at: Generated<Timestamp | null>;
  created_by_user_id: string;
  efficiency_percentual: number | null;
  fuel_type: string | null;
  id: Generated<string>;
  inventory_id: string;
  n2oemission: Generated<number>;
  name: string | null;
  period: Generated<string>;
  quantity: number;
  quantity_unit: string | null;
  scopecategory_id: string;
  totalco2emission: Generated<number>;
  unit_id: string;
  updated_at: Timestamp | null;
}

export interface GhgScope2category4responses {
  co2emission: Generated<number>;
  created_at: Generated<Timestamp | null>;
  created_by_user_id: string;
  energy_type: string | null;
  id: Generated<string>;
  inventory_id: string;
  period: Generated<string>;
  quantity: number;
  quantity_unit: string | null;
  scopecategory_id: string;
  totalco2emission: Generated<number>;
  unit_id: string;
  updated_at: Timestamp | null;
}

export interface GhgScope3category10responses {
  ch4emission: Generated<number>;
  co2emission: Generated<number>;
  created_at: Generated<Timestamp | null>;
  created_by_user_id: string;
  gas: string | null;
  id: Generated<string>;
  inventory_id: string;
  n2oemission: Generated<number>;
  name: string | null;
  period: Generated<string>;
  quantity: number;
  quantity_unit: string | null;
  scopecategory_id: string;
  totalco2emission: Generated<number>;
  unit_id: string;
  updated_at: Timestamp | null;
}

export interface GhgScope3category11responses {
  ch4emission: Generated<number>;
  co2emission: Generated<number>;
  created_at: Generated<Timestamp | null>;
  created_by_user_id: string;
  gas: string | null;
  id: Generated<string>;
  inventory_id: string;
  n2oemission: Generated<number>;
  name: string | null;
  period: Generated<string>;
  quantity: number;
  quantity_unit: string | null;
  scopecategory_id: string;
  totalco2emission: Generated<number>;
  unit_id: string;
  updated_at: Timestamp | null;
}

export interface GhgScope3category12responses {
  ch4emission: Generated<number>;
  co2emission: Generated<number>;
  created_at: Generated<Timestamp | null>;
  created_by_user_id: string;
  gas: string | null;
  id: Generated<string>;
  inventory_id: string;
  n2oemission: Generated<number>;
  name: string | null;
  period: Generated<string>;
  quantity: number;
  quantity_unit: string | null;
  scopecategory_id: string;
  totalco2emission: Generated<number>;
  unit_id: string;
  updated_at: Timestamp | null;
}

export interface GhgScope3category13responses {
  ch4emission: Generated<number>;
  co2emission: Generated<number>;
  created_at: Generated<Timestamp | null>;
  created_by_user_id: string;
  gas: string | null;
  id: Generated<string>;
  inventory_id: string;
  n2oemission: Generated<number>;
  name: string | null;
  period: Generated<string>;
  quantity: number;
  quantity_unit: string | null;
  scopecategory_id: string;
  totalco2emission: Generated<number>;
  unit_id: string;
  updated_at: Timestamp | null;
}

export interface GhgScope3category14responses {
  ch4emission: Generated<number>;
  co2emission: Generated<number>;
  created_at: Generated<Timestamp | null>;
  created_by_user_id: string;
  gas: string | null;
  id: Generated<string>;
  inventory_id: string;
  n2oemission: Generated<number>;
  name: string | null;
  period: Generated<string>;
  quantity: number;
  quantity_unit: string | null;
  scopecategory_id: string;
  totalco2emission: Generated<number>;
  unit_id: string;
  updated_at: Timestamp | null;
}

export interface GhgScope3category15responses {
  ch4emission: Generated<number>;
  co2emission: Generated<number>;
  created_at: Generated<Timestamp | null>;
  created_by_user_id: string;
  gas: string | null;
  id: Generated<string>;
  inventory_id: string;
  n2oemission: Generated<number>;
  name: string | null;
  period: Generated<string>;
  quantity: number;
  quantity_unit: string | null;
  scopecategory_id: string;
  totalco2emission: Generated<number>;
  unit_id: string;
  updated_at: Timestamp | null;
}

export interface GhgScope3category1responses {
  ch4emission: Generated<number>;
  co2emission: Generated<number>;
  created_at: Generated<Timestamp | null>;
  created_by_user_id: string;
  gas: string | null;
  id: Generated<string>;
  inventory_id: string;
  n2oemission: Generated<number>;
  name: string | null;
  period: Generated<string>;
  quantity: number;
  quantity_unit: string | null;
  scopecategory_id: string;
  totalco2emission: Generated<number>;
  unit_id: string;
  updated_at: Timestamp | null;
}

export interface GhgScope3category2responses {
  ch4emission: Generated<number>;
  co2emission: Generated<number>;
  created_at: Generated<Timestamp | null>;
  created_by_user_id: string;
  gas: string | null;
  id: Generated<string>;
  inventory_id: string;
  n2oemission: Generated<number>;
  name: string | null;
  period: Generated<string>;
  quantity: number;
  quantity_unit: string | null;
  scopecategory_id: string;
  totalco2emission: Generated<number>;
  unit_id: string;
  updated_at: Timestamp | null;
}

export interface GhgScope3category3responses {
  ch4emission: Generated<number>;
  co2emission: Generated<number>;
  created_at: Generated<Timestamp | null>;
  created_by_user_id: string;
  gas: string | null;
  id: Generated<string>;
  inventory_id: string;
  n2oemission: Generated<number>;
  name: string | null;
  period: Generated<string>;
  quantity: number;
  quantity_unit: string | null;
  scopecategory_id: string;
  totalco2emission: Generated<number>;
  unit_id: string;
  updated_at: Timestamp | null;
}

export interface GhgScope3category4responses {
  biodiesel_ch4: Generated<number>;
  biodiesel_n2o: Generated<number>;
  biogenicco2emission: Generated<number>;
  calcule_approach: string | null;
  ch4emission: Generated<number>;
  co2emission: Generated<number>;
  common_info: string | null;
  created_at: Generated<Timestamp | null>;
  created_by_user_id: string;
  diesel_ch4: Generated<number>;
  diesel_co2: Generated<number>;
  diesel_n2o: Generated<number>;
  distance: Generated<number>;
  fuel: string | null;
  full_trip: Generated<boolean | null>;
  gas: string | null;
  id: Generated<string>;
  inventory_id: string;
  modal: string | null;
  modal_type: string | null;
  n2oemission: Generated<number>;
  name: string | null;
  period: Generated<string>;
  quantity: Generated<number>;
  quantity_unit: string | null;
  scopecategory_id: string;
  totalco2emission: Generated<number>;
  transported_weight: Generated<number | null>;
  unit_id: string;
  updated_at: Timestamp | null;
  year: string | null;
}

export interface GhgScope3category5responses {
  ch4emission: Generated<number>;
  co2emission: Generated<number>;
  created_at: Generated<Timestamp | null>;
  created_by_user_id: string;
  gas: string | null;
  id: Generated<string>;
  inventory_id: string;
  n2oemission: Generated<number>;
  name: string | null;
  period: Generated<string>;
  quantity: number;
  quantity_unit: string | null;
  scopecategory_id: string;
  totalco2emission: Generated<number>;
  unit_id: string;
  updated_at: Timestamp | null;
}

export interface GhgScope3category6responses {
  auto_anual_comsumption: Generated<number>;
  biodiesel_ch4: Generated<number>;
  biodiesel_n2o: Generated<number>;
  biogenicco2emission: Generated<number>;
  ch4emission: Generated<number>;
  co2emission: Generated<number>;
  common_info: string | null;
  created_at: Generated<Timestamp | null>;
  created_by_user_id: string;
  diesel_ch4: Generated<number>;
  diesel_co2: Generated<number>;
  diesel_n2o: Generated<number>;
  distance: Generated<number>;
  full_trip: Generated<boolean>;
  gas: string | null;
  id: Generated<string>;
  inventory_id: string;
  modal: string | null;
  modal_type: string | null;
  n2oemission: Generated<number>;
  name: string | null;
  number_of_times: Generated<number>;
  period: Generated<string>;
  quantity: number;
  quantity_unit: string | null;
  scopecategory_id: string;
  totalco2emission: Generated<number>;
  unit_id: string;
  updated_at: Timestamp | null;
}

export interface GhgScope3category7responses {
  biodiesel_ch4: Generated<number>;
  biodiesel_n2o: Generated<number>;
  biogenicco2emission: Generated<number>;
  ch4emission: Generated<number>;
  co2emission: Generated<number>;
  common_info: string | null;
  created_at: Generated<Timestamp | null>;
  created_by_user_id: string;
  days_worked: Generated<number>;
  diesel_ch4: Generated<number>;
  diesel_co2: Generated<number>;
  diesel_n2o: Generated<number>;
  distance: Generated<number>;
  full_trip: Generated<boolean>;
  gas: string | null;
  id: Generated<string>;
  inventory_id: string;
  modal: string | null;
  modal_type: string | null;
  n2oemission: Generated<number>;
  name: string | null;
  number_of_times: Generated<number>;
  period: Generated<string>;
  quantity: number;
  quantity_unit: string | null;
  scopecategory_id: string;
  totalco2emission: Generated<number>;
  unit_id: string;
  updated_at: Timestamp | null;
}

export interface GhgScope3category8responses {
  ch4emission: Generated<number>;
  co2emission: Generated<number>;
  created_at: Generated<Timestamp | null>;
  created_by_user_id: string;
  gas: string | null;
  id: Generated<string>;
  inventory_id: string;
  n2oemission: Generated<number>;
  name: string | null;
  period: Generated<string>;
  quantity: number;
  quantity_unit: string | null;
  scopecategory_id: string;
  totalco2emission: Generated<number>;
  unit_id: string;
  updated_at: Timestamp | null;
}

export interface GhgScope3category9responses {
  biodiesel_ch4: Generated<number>;
  biodiesel_n2o: Generated<number>;
  biogenicco2emission: Generated<number>;
  calcule_approach: string | null;
  ch4emission: Generated<number>;
  co2emission: Generated<number>;
  common_info: string | null;
  created_at: Generated<Timestamp | null>;
  created_by_user_id: string;
  diesel_ch4: Generated<number>;
  diesel_co2: Generated<number>;
  diesel_n2o: Generated<number>;
  distance: Generated<number>;
  fuel: string | null;
  full_trip: Generated<boolean>;
  gas: string | null;
  id: Generated<string>;
  inventory_id: string;
  modal: string | null;
  modal_type: string | null;
  n2oemission: Generated<number>;
  name: string | null;
  period: Generated<string>;
  quantity: number;
  quantity_unit: string | null;
  scopecategory_id: string;
  totalco2emission: Generated<number>;
  transported_weight: Generated<number>;
  unit_id: string;
  updated_at: Timestamp | null;
  year: string | null;
}

export interface GhgScopecategory {
  active: Generated<boolean>;
  category_type: string;
  created_at: Generated<Timestamp | null>;
  deadline_at: Timestamp | null;
  finalized: Generated<boolean>;
  finalized_at: Timestamp | null;
  id: Generated<string>;
  inventory_id: string;
  updated_at: Timestamp | null;
}

export interface GhgScopecategoryresponsible {
  comment: string | null;
  created_at: Generated<Timestamp | null>;
  email: string;
  id: Generated<string>;
  name: string;
  scopecategory_id: string;
  status: Generated<string>;
  unit_id: string;
  updated_at: Timestamp | null;
  user_id: string;
}

export interface ProfileEmailLogs {
  created_at: Timestamp;
  email: string;
  id: Generated<string>;
  type: string;
}

export interface ProfileEmailStats {
  count: number;
  created_at: Generated<Timestamp>;
  email: string;
  first_sent_at: Timestamp;
  id: Generated<string>;
  last_sent_at: Timestamp;
  type: string;
}

export interface ProfileForgotPasswordTokens {
  created_at: Generated<Timestamp | null>;
  expires_at: Timestamp;
  id: Generated<string>;
  is_used: Generated<boolean>;
  token: Generated<string>;
  updated_at: Timestamp | null;
  user_id: string;
}

export interface ProfileInviteUserTokens {
  created_at: Generated<Timestamp | null>;
  email: string;
  expires_at: Timestamp;
  id: Generated<string>;
  invited_by_id: string;
  is_used: Generated<boolean>;
  name: string;
  organization_id: string;
  role: string;
  token: Generated<string>;
  type: string;
  updated_at: Timestamp | null;
  user_id: string | null;
}

export interface ProfileOrganizationPlan {
  id: Generated<string>;
  organization_id: string;
  plan_id: string;
}

export interface ProfileOrganizations {
  cnpj: string | null;
  created_at: Generated<Timestamp>;
  created_by_user_id: string | null;
  id: Generated<string>;
  invoicing: string | null;
  logo_url: string | null;
  max_units: Generated<number>;
  name: string;
  number_of_collaborators: string | null;
  sector: string | null;
  status: Generated<string>;
  updated_at: Timestamp | null;
}

export interface ProfilePlans {
  created_at: Generated<Timestamp>;
  datasets: Generated<Json>;
  description: string | null;
  id: Generated<string>;
  name: string;
  price: number;
  updated_at: Timestamp | null;
}

export interface ProfileRegisterTokens {
  created_at: Generated<Timestamp | null>;
  email_token: string;
  expires_at: Timestamp;
  id: Generated<string>;
  is_used: Generated<boolean>;
  token: Generated<string | null>;
  updated_at: Timestamp | null;
  user_id: string;
}

export interface ProfileUnitConfigs {
  controller_unit_id: string | null;
  created_at: Generated<Timestamp>;
  hierarchy: number;
  id: Generated<string>;
  operational_control: boolean;
  percentage_share: number;
  unit_id: string;
  updated_at: Timestamp | null;
}

export interface ProfileUnits {
  city: string | null;
  cnpj: string | null;
  country: string;
  created_at: Generated<Timestamp>;
  id: Generated<string>;
  name: string;
  organization_id: string | null;
  sector: string | null;
  state: string | null;
  updated_at: Timestamp | null;
}

export interface ProfileUserOrganization {
  id: Generated<string>;
  organization_id: string;
  permission: string;
  user_id: string;
  validated: Generated<boolean>;
}

export interface ProfileUsers {
  active: Generated<boolean>;
  created_at: Generated<Timestamp>;
  creation_type: Generated<string>;
  email: string;
  id: Generated<string>;
  name: string;
  password: string | null;
  password_migrated: Generated<boolean>;
  phone: string | null;
  updated_at: Timestamp | null;
}

export interface DB {
  "ghg.evidence": GhgEvidence;
  "ghg.inventories": GhgInventories;
  "ghg.inventory_unit_configs": GhgInventoryUnitConfigs;
  "ghg.inventory_units": GhgInventoryUnits;
  "ghg.scope1category1responses": GhgScope1category1responses;
  "ghg.scope1category2responses": GhgScope1category2responses;
  "ghg.scope1category3responses": GhgScope1category3responses;
  "ghg.scope1category4responses": GhgScope1category4responses;
  "ghg.scope1category5responses": GhgScope1category5responses;
  "ghg.scope1category6responses": GhgScope1category6responses;
  "ghg.scope1category7responses": GhgScope1category7responses;
  "ghg.scope1category8responses": GhgScope1category8responses;
  "ghg.scope2category1responses": GhgScope2category1responses;
  "ghg.scope2category2responses": GhgScope2category2responses;
  "ghg.scope2category3responses": GhgScope2category3responses;
  "ghg.scope2category4responses": GhgScope2category4responses;
  "ghg.scope3category10responses": GhgScope3category10responses;
  "ghg.scope3category11responses": GhgScope3category11responses;
  "ghg.scope3category12responses": GhgScope3category12responses;
  "ghg.scope3category13responses": GhgScope3category13responses;
  "ghg.scope3category14responses": GhgScope3category14responses;
  "ghg.scope3category15responses": GhgScope3category15responses;
  "ghg.scope3category1responses": GhgScope3category1responses;
  "ghg.scope3category2responses": GhgScope3category2responses;
  "ghg.scope3category3responses": GhgScope3category3responses;
  "ghg.scope3category4responses": GhgScope3category4responses;
  "ghg.scope3category5responses": GhgScope3category5responses;
  "ghg.scope3category6responses": GhgScope3category6responses;
  "ghg.scope3category7responses": GhgScope3category7responses;
  "ghg.scope3category8responses": GhgScope3category8responses;
  "ghg.scope3category9responses": GhgScope3category9responses;
  "ghg.scopecategory": GhgScopecategory;
  "ghg.scopecategoryresponsible": GhgScopecategoryresponsible;
  "profile.email_logs": ProfileEmailLogs;
  "profile.email_stats": ProfileEmailStats;
  "profile.forgot_password_tokens": ProfileForgotPasswordTokens;
  "profile.invite_user_tokens": ProfileInviteUserTokens;
  "profile.organization_plan": ProfileOrganizationPlan;
  "profile.organizations": ProfileOrganizations;
  "profile.plans": ProfilePlans;
  "profile.register_tokens": ProfileRegisterTokens;
  "profile.unit_configs": ProfileUnitConfigs;
  "profile.units": ProfileUnits;
  "profile.user_organization": ProfileUserOrganization;
  "profile.users": ProfileUsers;
}
